version: '3'
services:
  selenium-hub:
    image: selenium/standalone-firefox:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"
  crawler-jus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
#    depends_on:
#      - selenium-hub
#    links:
#      - selenium-hub